### PR TITLE
Added Git repository configuration support

### PR DESCRIPTION
**Pull request by mosch**
Configuration settings will get lazy-loaded per key. 
If a key is changed, the "local cache" will be removed to avoid "type specific problems".
Also changed the behavior. There is no need to merge the global configuration with the local configuration if you do not pass --local or --global to the "git config" command.

Trimmed the return value of the GitCommand class, because newline problems occurred during the unittests.

### CODE REVIEW

**Comment by mosch** [comment]
I just realized that i violated your code conventions. I used 2 instead of 4 whitespaces… 
I will fix that in a separate pull request.

**Comment by ornicar** [comment]
You should work in a branch and do the PR with this branch. It makes it easier to fix a PR without opening a new one.

About CS, well, the best would be to move everything to the PEAR coding standards, that Zend Framework and Symfony2 use.

**Comment by mosch** [comment]
Okay, thanks for the advice. I will create a branch and do everything in my branch. 

About CS, moving everything to the PEAR coding standards is exactly the wish I had - because I need to integrate it into Symfony2. I have some time - so I can do this.

**Comment by ornicar** [comment]
That would be awesome!

**Comment by mosch** [comment]
Everything is now in a new pull request branched pull request: https://github.com/ornicar/php-git-repo/pull/3

**Pull request closed without merging**
